package ist.yaabex.tests;

public class ExpectedOutput {
	
	public final String[] abeatifulMind = {
									"Mathematicians won the war.                                                           --- Os matemáticos venceram a guerra.",
									"Mathematicians broke the Japanese codes... and built the A-bomb.                      --- Os matemáticos decifraram os códigos japoneses... e construíram a bomba atómica.",
									"Mathematicians, like you.                                                             --- Matemáticos como vocês.",
									"The stated goal of the Soviets is global Communism.                                   --- A meta estabelecida pelos soviéticos é o comunismo global.",
									"In medicine or economics... in technology or space... battle lines are being drawn.   --- Na medicina ou na economia, na tecnologia ou no espaço, começam a criar-se linhas de batalha.",
									"To triumph, we need results... publishable, applicable results.                       --- Para triunfarmos, precisamos de resultados... que possam ser anunciados e utilizados.",
									"Now who among you will be the next Morse?                                             --- Qual de vós será o próximo Morse?",
									"The next Einstein?                                                                    --- O próximo Einstein?",
									"Who among you will be the vanguard of democracy... freedom, and discovery?            --- Qual de vós será a vanguarda da democracia, liberdade e descoberta?",
									"Today, we bequeath America's future into your able hands.                             --- Hoje, depositamos o futuro da América nas vossas mãos capazes.",
									"Welcome to Princeton, gentlemen.                                                      --- Bem-vindos a Princeton, senhores.",
									"It's not enough Hansen won the Carnegie Scholarship.                                  --- Não basta o Hansen ter ganho a Bolsa Carnegie.",
									"No, he wants it all for himself.                                                      --- Não, tem de ter tudo só para ele.",
									"It's the first time the Carnegie Prize has been split.                                --- É a primeira vez que repartem o Prémio Carnegie.",
									"Hansen's all bent.                                                                    --- Ele ficou aborrecido.",
									"He has his sights set on Wheeler Lab, MIT's military think-tank.                      --- Anda de olho no Wheeler Lab, o novo grupo militar de investigação do ITM.",
									"They're only taking one this year.                                                    --- Este ano, só admitem um aluno.",
									"Hansen's used to being picked first.                                                  --- Habituou-se a ser escolhido primeiro.",
									"Yeah, he's wasted on math.                                                            --- É mal empregue em matemática.",
									"He should be running for president.                                                   --- Devia candidatar-se a presidente.",
									"- Why is that?                                                                        --- - Porquê?",
									"- I like to think it's because I'm a Ione wolf.                                       --- - Julgo que é por eu ser um solitário.",
									"But mainly it's because people don't like me.                                         --- Mas é sobretudo porque as pessoas não gostam de mim.",
									"There are certain endeavors... where your lack of personal connection would be considered an advantage. --- Há certos empreendimentos... em que a falta de ligação pessoal é considerada uma vantagem.",
									"- This is a secure area.                                                              --- - Esta é uma área interdita.",
									"- They know me.                                                                       --- - Eles conhecem-me.",
									"Have you ever been here?                                                              --- Já aqui esteve?",
									"We were told in our initial briefing these warehouses were abandoned.                 --- Nas instruções iniciais, disseram-nos que eram armazéns abandonados.",
									"That's not precisely accurate.                                                        --- Não são bem isso.",
									"By telling you this... I am increasing your security clearance to top secret.         --- Ao contar-lhe o que lhe vou dizer, aumento o seu acesso a informações secretas.",
									"Disclosure of secure information can result in imprisonment.                          --- Revelar informações confidenciais pode resultar em prisão.",
									"Get it?                                                                               --- Percebeu?",
									"What operation?                                                                       --- Qual é a operação?",
									"Those are a good idea.                                                                --- Esses são uma boa ideia.",
									"This factory is in Berlin, we seized it at the end of the war.                        --- Esta fábrica é em Berlim. Confiscámo-la no fim da guerra.",
									"Nazi engineers were attempting to build a portable atomic bomb.                       --- Os engenheiros nazis tentavam construir uma bomba atómica portátil.",
									"The Soviets reached this facility before we did, and we lost the damn thing.          --- Os soviéticos chegaram primeiro a estas instalações e nós perdemo-la.",
									"The routing orders at the Pentagon.                                                   --- As ordens de marcha no Pentágono.",
									"They were about this, weren't they?                                                   --- Referiam-se a isto, não era?",
									"The Soviets aren't as unified as people believe.                                      --- Os soviéticos não são tão unidos como se pensa.",
									"A faction of the Red Army calling itself Novaya Svoboda... the \"New Freedom,\" has control of the bomb... and intends to detonate it on U.S. soil. --- Uma facção do Exército Vermelho, que se intitula Novaya Svoboda, ou \"Nova Liberdade\", tem a bomba em seu poder... e pretende detoná-la em solo americano.",
									"Their plan is to incur maximum civilian casualties.                                   --- O plano deles é causar o máximo de vítimas civis.",
									"Whew.                                                                                 --- ",
									"Hmm?                                                                                  --- ",
									"Hmm.                                                                                  --- ",
									"But why, with all your obvious wit and charm?                                         --- Apesar dessa tua notória inteligência e charme?",
									"The truth is that I... I don't like people much. And they don't much like me.         --- Na verdade, não gosto muito das pessoas, nem elas gostam muito de mim."};

	private final String[] americanBeauty = {"I need a father who's a role model, not some horny geek boy... who's going to spray his shorts whenever I bring a girlfriend home from school. --- Preciso de um pai que me sirva de exemplo, não um nabo que se vem nas cuecas quando trago uma colega a casa.",
									"What a lame-o.                                                                        --- É cá um anormal.",
									"Someone really should just put him out of his misery.                                 --- Quem dera que alguém despachasse o gajo de vez.",
									"You want me to kill him for you?                                                      --- Queres que o mate?",
									"Yeah.                                                                                 --- Quero.",
									"Would you?                                                                            --- Fazes-me isso?",
									"My name is Lester Burnham.                                                            --- Chamo-me Lester Burnham.",
									"This is my neighborhood.                                                              --- Moro aqui, neste bairro.",
									"This is my street.                                                                    --- Esta é a minha rua.",
									"This is my life.                                                                      --- Esta é a minha vida.",
									"I'm 42 years old. In less than a year, I'll be dead.                                  --- Tenho quarenta e dois anos e dentro de menos um ano, estarei morto.",
									"Of course, I don't know that yet.                                                     --- É claro, isso não sei ainda.",
									"And in a way, I'm dead already.                                                       --- Aliás, de certa maneira, morto já eu estou.",
									"Look at me: jerking off in the shower.                                                --- Olhem para mim, masturbando-me no duche.",
									"This will be the high point of my day. It's all downhill from here.                   --- E este será o ponto alto do meu dia.",
									"That's my wife, Carolyn.                                                              --- Eis a minha mulher, Carolyn.",
									"See the way the handle on those pruning shears matches her gardening clogs?           --- Repararam que a pega da podadeira é da mesma cor que os sapatos para jardinagem?",
									"That's not an accident.                                                               --- Não é um acaso.",
									"Hush, Bitsy!                                                                          --- ",
									"- That's our next-door neighbor, Jim.                                                 --- Aquele é o nosso vizinho Jim.",
									"And that's his lover, Jim.                                                            --- E aquele é o amante dele... Jim."};
	
	private final String[] findingNemo = {"Yes, Marlin. I see it.                                                                --- - Sim, Marlin, estou a ver.",
								    "It's beautiful.                                                                       --- É lindo.",
									"So, Coral, when you said you wanted an ocean view, you didn't think you were going to get the whole ocean, did you? --- Coral, quando disseste que querias vista para o mar não pensaste que te calharia o oceano inteiro, pois não?",
									"- My man delivered.                                                                   --- - Esteve bem.",
									"Other clownfish had their eyes on this place.                                         --- \"Havia muitos outros peixes a quererem esta casa.\"",
									"- You remember how we met?                                                            --- - Lembras-te como nos conhecemos?",
									"- I try not to.                                                                       --- - Tento esquecer-me.",
									"Hold my fin.                                                                          --- Não me largues a barbatana.",
									"Actually, the mollusc isn't moving.                                                   --- Aliás, o molusco não se está a mexer.",
									"He's in one place.                                                                    --- Ele está parado.",
									"Can I go play too?                                                                    --- Papá, também posso ir brincar?",
									"- Bye, Nemo.                                                                          --- - Adeus, Nemo.",
									"- Bye, Dad.                                                                           --- - Adeus, papá.",
									"- For a clownfish, he isn't that funny.                                               --- Para um peixe-palhaço, ele não tem muita graça.",
									"- Pity.                                                                               --- É pena.",
									"Stop.                                                                                 --- Pára!",
									"You take one more move, mister...                                                     --- Rapazinho, se deres mais uma barbatanada...",
									"Don't you dare.                                                                       --- Não te atrevas!",
									"If you put one fin on that boat...                                                    --- Se puseres uma barbatana nesse barco...",
									"Are you listening to me?                                                              --- Estás a ouvir?",
									"- Can't complain.                                                                     --- - Não me posso queixar.",
									"- Good.                                                                               --- - Óptimo.",
									"Now, Dory, I want you to tell me, do you see anything?   -                            -- Agora quero que me digas... se vês alguma coisa.",
									"I see a...- I see a light.                                                            --- Vejo... vejo uma luz.",
									"- A light?                                                                            --- - Uma luz?",
									"Yeah.                                                                                 --- - Sim.",
									"Over there.                                                                           --- Ali ao fundo.",
									"Hey, conscience, am I dead?                                                           --- - Consciência, eu estou morta?",
									"I see it, too.                                                                        --- - Não, eu também a estou a ver.",
									"- Do your stripes come off?                                                           --- - As tuas riscas saem?",
									"- I need to breathe.                                                                  --- -",
									"Did you cross the jellyfish forest?                                                   --- - Passaste a floresta de alforrecas?",
									"- One at a time.                                                                      --- - Um de cada vez!",
									"- Mr Fish, did you die?                                                               --- - Sr. Peixe, o senhor morreu?",
									"I know your son.                                                                      --- Conheço o teu filho.",
									"He's orange. He's got a gimpy fin on one side.                                        --- É cor-de-laranja e tem uma barbatana defeituosa.",
									"That's Nemo!                                                                          --- - É o Nemo!",
									"Wake up!                                                                              --- Acorda!",
									"- To the top of Mt. Wannahockaloogie.                                                 --- Depressa, para o cimo do Monte Wannahockaloogie!",
									"Why are you sleeping?                                                                 --- Porque é que estás a dormir?",
									"- Hurry!                                                                              --- - Depressa!", 
									"- Bloat!                                                                              --- - Balão!",
									"Ring of Fire!                                                                         --- Anel de Fogo!"};
	private String[] expected;
	public ExpectedOutput(final String subtitleName) {
		switch (subtitleName) {
			case "abeautifulMind"	: expected = abeatifulMind;		break;
			case "americanBeauty"	: expected = americanBeauty;	break;
			case "findingNemo"		: expected = findingNemo;		break;
		}
	}
	
	public String[] getExpected(){
		return expected;
	}
}
